### ISSUE TITLE
Add a median_geom()

### ISSUE THREAD

**Issue by jthomasmock** [nflverse/nflplotR#1]
It'd be great to have an automatic way to plot the median/mean for the vertical/horizontal lines. This can be relatively lightweight via `{{col}}`or you could go further into the `grob` world to automatically bring in the x/y `aes()`. I know Ben and others do a lot of logo plots that also include relative mean/medians by axis.

``` r
library(ggplot2)
median_geom <- function(x,y, color = "red", linetype = "dashed"){
  list(
    geom_vline(aes(xintercept = median({{x}})), color = color, linetype = linetype),
    geom_hline(aes(yintercept = median({{y}})), color = color, linetype = linetype)
  )
}
ggplot(mtcars) +
  geom_point(aes(x = disp, y = mpg)) +
  median_geom(disp, mpg)
```

![](https://i.imgur.com/F2Rf1Wq.png)

<sup>Created on 2021-09-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mrcaseb** [comment]
This has now been implemented with a more ggplot2 conform approach. Also added a mean geom. 

See examples here https://nflverse.github.io/nflplotR/reference/geom_median_lines.html
