### ISSUE TITLE
[feature req] ggcomet?

### ISSUE THREAD

**Issue by tanho63** [nflverse/nflplotR#17]
It would be cool if there was a ggcomet geom that produces something like https://thef5.substack.com/p/how-to-comet-plot

**Comment by mrcaseb** [comment]
I think thie is beyond the scope of nflplotR. I think the best way would be a separate {ggcomet} package

**Comment by tanho63** [comment]
Yeah, ggcomet seems a bit too small to have as a standalone package but a bit out of scope here
